/* wickra-backtest C ABI — generated by cbindgen. Do not edit by hand. */

#ifndef WICKRA_BACKTEST_H
#define WICKRA_BACKTEST_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define WICKRA_BT_OK 0

/**
 * The inputs or spec were invalid (message in `*out_json`).
 */
#define WICKRA_BT_ERROR 1

/**
 * A null argument was passed, or an internal panic was caught.
 */
#define WICKRA_BT_PANIC 2

/**
 * An in-progress streaming backtest. Opaque to C; create it with
 * [`wickra_backtest_stream_new`] and release it with
 * [`wickra_backtest_stream_free`], or by calling
 * [`wickra_backtest_stream_finish_json`], which consumes it.
 */
typedef struct WickraBacktestStream WickraBacktestStream;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 * The six array pointers must each point to `n` elements; `spec_json` must be a
 * valid NUL-terminated string; `out_json` must be a valid pointer to a
 * `char *`. On success `*out_json` receives a string to free with
 * [`wickra_backtest_free_string`].
 */
int wickra_backtest_run(const double *open,
                        const double *high,
                        const double *low,
                        const double *close,
                        const double *volume,
                        const int64_t *time,
                        uintptr_t n,
                        const char *spec_json,
                        double capital,
                        char **out_json);

/**
 * Run a backtest from a single JSON request (see `RunRequest`: a document with
 * `spec`, `candles`, optional `capital` and optional `reference` / `derivs` /
 * `books` / `trades` / `sections` feeds), writing the report JSON to
 * `*out_json` (free it with [`wickra_backtest_free_string`]).
 *
 * # Safety
 * `request_json` must be a valid NUL-terminated string; `out_json` must be a
 * valid pointer to a `char *`.
 */
int wickra_backtest_run_json(const char *request_json, char **out_json);

/**
 * Free a string returned by [`wickra_backtest_run`].
 *
 * # Safety
 * `s` must be a pointer returned by [`wickra_backtest_run`] (and not already
 * freed), or null.
 */
void wickra_backtest_free_string(char *s);

/**
 * The library version as a static NUL-terminated string (do not free).
 */
const char *wickra_backtest_version(void);

/**
 * Start a streaming backtest from a JSON strategy spec.
 *
 * On success writes the handle to `*out_handle` and returns [`WICKRA_BT_OK`].
 * On failure writes the message to `*out_err` and leaves `*out_handle` null.
 *
 * # Safety
 * `spec_json` must be a valid NUL-terminated string; `out_handle` and `out_err`
 * must be valid pointers. Any string written to `*out_err` is freed with
 * [`wickra_backtest_free_string`].
 */
int wickra_backtest_stream_new(const char *spec_json,
                               double capital,
                               struct WickraBacktestStream **out_handle,
                               char **out_err);

/**
 * Advance the backtest by one candle.
 *
 * # Safety
 * `handle` must come from [`wickra_backtest_stream_new`] and must not have been
 * freed; `out_err` must be a valid pointer.
 */
int wickra_backtest_stream_step(struct WickraBacktestStream *handle,
                                double open,
                                double high,
                                double low,
                                double close,
                                double volume,
                                int64_t time,
                                char **out_err);

/**
 * Advance the backtest by one bar described as a JSON document.
 *
 * `step_json` is a [`StepRequest`]: `{"candle": {...}, "feeds": {...}}`, where
 * `feeds` is optional and carries this bar's `reference`, `deriv`, `orderbook`,
 * `trades` and `cross_section`. Use this rather than
 * [`wickra_backtest_stream_step`] whenever the strategy reads a side feed —
 * the scalar form can only supply OHLCV.
 *
 * # Safety
 * `handle` must come from [`wickra_backtest_stream_new`] and must not have been
 * freed; `step_json` must be a valid NUL-terminated string; `out_err` must be a
 * valid pointer.
 */
int wickra_backtest_stream_step_json(struct WickraBacktestStream *handle,
                                     const char *step_json,
                                     char **out_err);

/**
 * The number of closed trades so far.
 *
 * # Safety
 * `handle` must come from [`wickra_backtest_stream_new`] and must not have been
 * freed; `out_count` must be a valid pointer.
 */
int wickra_backtest_stream_num_trades(const struct WickraBacktestStream *handle,
                                      uintptr_t *out_count);

/**
 * The most recent equity point as JSON, or the JSON literal `null` while no bar
 * has been fed yet.
 *
 * # Safety
 * `handle` must come from [`wickra_backtest_stream_new`] and must not have been
 * freed; `out_json` must be a valid pointer. Free the string with
 * [`wickra_backtest_free_string`].
 */
int wickra_backtest_stream_latest_equity_json(const struct WickraBacktestStream *handle,
                                              char **out_json);

/**
 * The whole equity curve so far, as a JSON array.
 *
 * # Safety
 * `handle` must come from [`wickra_backtest_stream_new`] and must not have been
 * freed; `out_json` must be a valid pointer. Free the string with
 * [`wickra_backtest_free_string`].
 */
int wickra_backtest_stream_equity_json(const struct WickraBacktestStream *handle, char **out_json);

/**
 * Close any open position, produce the report JSON, and consume the handle.
 *
 * The handle is freed whatever the outcome: it must not be used again, and must
 * not be passed to [`wickra_backtest_stream_free`].
 *
 * # Safety
 * `handle` must come from [`wickra_backtest_stream_new`] and must not have been
 * freed; `out_json` must be a valid pointer. Free the string with
 * [`wickra_backtest_free_string`].
 */
int wickra_backtest_stream_finish_json(struct WickraBacktestStream *handle, char **out_json);

/**
 * Release a handle without producing a report.
 *
 * # Safety
 * `handle` must come from [`wickra_backtest_stream_new`] and must not have been
 * freed or consumed by [`wickra_backtest_stream_finish_json`]. Null is a no-op.
 */
void wickra_backtest_stream_free(struct WickraBacktestStream *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WICKRA_BACKTEST_H */
