/* wickra-backtest C ABI — generated by cbindgen. Do not edit by hand. */

#ifndef WICKRA_BACKTEST_H
#define WICKRA_BACKTEST_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success.
 */
#define WICKRA_BT_OK 0

/**
 * The inputs or spec were invalid (message in `*out_json`).
 */
#define WICKRA_BT_ERROR 1

/**
 * A null argument was passed, or an internal panic was caught.
 */
#define WICKRA_BT_PANIC 2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * # Safety
 * The six array pointers must each point to `n` elements; `spec_json` must be a
 * valid NUL-terminated string; `out_json` must be a valid pointer to a
 * `char *`. On success `*out_json` receives a string to free with
 * [`wickra_backtest_free_string`].
 */
int wickra_backtest_run(const double *open,
                        const double *high,
                        const double *low,
                        const double *close,
                        const double *volume,
                        const int64_t *time,
                        uintptr_t n,
                        const char *spec_json,
                        double capital,
                        char **out_json);

/**
 * Run a backtest from a single JSON request (see `RunRequest`: a document with
 * `spec`, `candles`, optional `capital` and optional `reference` / `derivs` /
 * `books` / `trades` / `sections` feeds), writing the report JSON to
 * `*out_json` (free it with [`wickra_backtest_free_string`]).
 *
 * # Safety
 * `request_json` must be a valid NUL-terminated string; `out_json` must be a
 * valid pointer to a `char *`.
 */
int wickra_backtest_run_json(const char *request_json, char **out_json);

/**
 * Free a string returned by [`wickra_backtest_run`].
 *
 * # Safety
 * `s` must be a pointer returned by [`wickra_backtest_run`] (and not already
 * freed), or null.
 */
void wickra_backtest_free_string(char *s);

/**
 * The library version as a static NUL-terminated string (do not free).
 */
const char *wickra_backtest_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WICKRA_BACKTEST_H */
